### ISSUE TITLE
both dependency and peer dependency on React

### ISSUE THREAD

**Issue by cellog** [marcusmolchany/react-jazzicon#10]
react-jazzicon depends on React 16 but has a peer dependency of React 15. This results in an npm warning. It would be great if both react and react-dom were peer dependencies with version ranges

**Comment by marcusmolchany** [comment]
hey thanks for calling this out @cellog, i will take a look tonight

**Comment by marcusmolchany** [comment]
got busy and haven't had a chance to look at this. if someone wants to pr i'll review
